<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Proposed compositions for dishes that are not a single food.
 *
 * A model can name what is in plov far better than a hand-written table can
 * enumerate a cuisine, but it is weakest exactly where it matters most: the
 * gram weights the calories are computed from. So a proposal is stored as a
 * candidate with a review state, never as fact. Only reviewed and
 * curated_override rows are served to everyone without asking; a generated row
 * is offered to the person who caused it, with its uncertainty visible.
 *
 * Composition is stored as ratios of a normalised serving, not as one portion
 * size, so "a small plate" and "a large plate" scale the same recipe instead of
 * needing separate rows.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('recipe_candidates', function (Blueprint $table) {
            $table->id();

            // Identity of the thing being described.
            $table->string('dish')->comment('normalised dish name');
            $table->string('locale', 8);
            $table->string('variant')->nullable()->comment('"meat plov", "vegetarian"');
            $table->string('preparation')->nullable()->comment('fried, boiled, baked');

            // Identity of how it was produced. A recipe generated by an older
            // model or an older prompt is not interchangeable with a new one,
            // so the key carries all of it and old rows simply stop matching.
            $table->string('model_version');
            $table->unsignedSmallInteger('schema_version');
            $table->unsignedSmallInteger('recipe_version')->default(1);

            $table->string('cache_key', 64)->unique()->comment('sha256 of the fields above');

            $table->enum('state', ['generated', 'user_confirmed', 'reviewed', 'curated_override'])
                ->default('generated')
                ->index();

            /** [{food, gramsLow, gramsHigh}], per one normalised serving. */
            $table->json('ingredients');
            /** What the model had to assume, shown to the user verbatim. */
            $table->json('assumptions')->nullable();
            $table->unsignedSmallInteger('serving_g')->comment('the serving the grams describe');

            $table->unsignedInteger('hits')->default(0);
            $table->unsignedInteger('confirmations')->default(0);
            $table->string('reviewed_by')->nullable();
            $table->timestamp('reviewed_at')->nullable();

            $table->timestamps();

            $table->index(['dish', 'locale', 'state']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('recipe_candidates');
    }
};
